import os
import re
import logging
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)
_groq_client = None


def _get_groq_client():
    global _groq_client
    if _groq_client is None:
        from groq import Groq
        _groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
    return _groq_client


def _get_embeddings():
    from models.embeddings import get_model, get_collection
    return get_model(), get_collection()

EMERGENCY_PATTERNS = [
    "not breathing", "not moving", "unconscious", "chest pain",
    "heavy bleeding", "bleeding won't stop", "baby not moving",
    "can't breathe", "fit", "convulsion", "severe headache sudden",
    "vision suddenly", "water broke", "cord prolapse",
    "baby swallowed", "accidental", "overdose", "suicide",
    "want to hurt", "want to die", "end my life",
]

EMERGENCY_RESPONSE = {
    "answer": (
        "🚨 **Please seek immediate medical help.**\n\n"
        "Based on what you've described, you need emergency care right now.\n\n"
        "**Call immediately:**\n"
        "- Emergency: **112**\n"
        "- NHM Helpline: **104**\n"
        "- iCall Mental Health: **9152987821**\n\n"
        "Please do not wait. Go to your nearest hospital emergency department now."
    ),
    "confidence": "emergency",
    "sources": [],
    "bypass_rag": True,
}

GROUNDED_SYSTEM_PROMPT = """You are Matrny, a maternal and infant health assistant for Indian mothers.

STRICT RULES — NEVER VIOLATE:
1. Answer ONLY using the CONTEXT provided below. Do not use any knowledge outside this context.
2. If the context does not contain enough information to answer the question, respond EXACTLY with: "I don't have reliable information on this topic in my knowledge base. Please consult your doctor or qualified healthcare provider for this question."
3. Never invent statistics, drug names, dosages, or medical procedures.
4. Never recommend stopping a prescribed medication.
5. Never diagnose a condition.
6. Always present both MBBS and Ayurvedic perspectives when both are available in the context.
7. Every factual claim must reference which source it came from.
8. If you are uncertain about ANY part of your answer, say so explicitly.

RESPONSE FORMAT — always use exactly this structure:
**MBBS Perspective:** [What modern medicine says, cited from context. If not in context: "Not found in current knowledge base."]

**Ayurvedic Perspective:** [What Ayurveda says, cited from context. If not in context: "Not found in current knowledge base."]

**Practical Tip:** [One concrete, safe, actionable tip. Only if supported by context.]

**Important:** This is AI-generated health information. Always consult a qualified doctor before making any health decisions.

**Sources:** [List exact source filenames from context]"""

HALLUCINATION_RED_FLAGS = [
    r"\d+\s*mg",
    r"\d+\s*ml",
    r"take \d+",
    r"dose of",
    r"studies show",
    r"research shows",
    r"according to dr",
    r"\d+% of",
]

DISCLAIMERS = {
    "auto_safe": (
        "\n\n---\n"
        "ℹ️ *This information is from verified health guidelines and traditional "
        "Ayurvedic sources. It is for general guidance only.*"
    ),
    "ai_generated": (
        "\n\n---\n"
        "⚠️ **AI-Generated Health Information**\n"
        "This answer is generated by AI from medical guidelines and Ayurvedic texts. "
        "It is NOT a substitute for professional medical advice. "
        "**Always consult your doctor or qualified healthcare provider before "
        "making any health decisions.**\n"
        "NHM Helpline: **104** | Emergency: **112**"
    ),
    "requires_doctor": (
        "\n\n---\n"
        "🚨 **Doctor Consultation Required**\n"
        "This question involves your specific medical situation and requires "
        "personalised advice from a qualified doctor. "
        "Please do not act on general information for this type of question.\n"
        "NHM Helpline: **104** | Emergency: **112**"
    ),
    "safety_fallback": (
        "\n\n---\n"
        "ℹ️ I don't have enough information to answer this reliably. "
        "Please consult a qualified healthcare provider.\n"
        "NHM Helpline: **104** | Emergency: **112**"
    ),
}


def check_emergency(message: str) -> bool:
    message_lower = message.lower()
    return any(pattern in message_lower for pattern in EMERGENCY_PATTERNS)


def check_retrieval_confidence(results: dict) -> dict:
    """Analyse ChromaDB retrieval results. Returns confidence assessment."""
    if not results.get("documents") or not results["documents"][0]:
        return {"should_answer": False, "reason": "no_chunks_found", "score": 0.0}

    distances = results["distances"][0]
    best_distance = min(distances)
    avg_distance = sum(distances) / len(distances)

    if best_distance > 0.7:
        return {
            "should_answer": False,
            "reason": "low_relevance",
            "score": round(1 - best_distance, 3),
        }

    sources = set(m["source"] for m in results["metadatas"][0])

    return {
        "should_answer": True,
        "reason": "sufficient_evidence",
        "score": round(1 - avg_distance, 3),
        "source_count": len(sources),
        "sources": list(sources),
    }


def classify_confidence_tier(question: str, retrieval_score: float, category: str) -> str:
    question_lower = question.lower()

    requires_doctor_keywords = [
        "dosage", "dose", "how much medicine", "can i take",
        "drug", "tablet", "capsule", "injection", "iv ",
        "bleeding heavily", "severe pain", "chest pain",
        "can't breathe", "unconscious", "emergency",
        "stopped moving", "baby not moving", "miscarriage",
        "preterm", "premature labour", "water broke",
        "seizure", "convulsion", "jaundice severe",
        "stop taking", "discontinue",
    ]

    auto_safe_keywords = [
        "recipe", "food", "eat", "diet", "nutrition", "meal",
        "exercise", "yoga", "walk", "massage technique",
        "breastfeeding position", "swaddle", "bath baby",
        "what to pack", "hospital bag", "baby clothes",
    ]

    if any(k in question_lower for k in requires_doctor_keywords):
        return "requires_doctor"

    if any(k in question_lower for k in auto_safe_keywords):
        if retrieval_score > 0.5:
            return "auto_safe"

    return "ai_generated"


def detect_potential_hallucination(answer: str, retrieved_chunks: list) -> dict:
    flags_found = []
    combined_context = " ".join(retrieved_chunks).lower()
    answer_lower = answer.lower()

    for pattern in HALLUCINATION_RED_FLAGS:
        matches = re.findall(pattern, answer_lower)
        if matches:
            for match in matches:
                if match not in combined_context:
                    flags_found.append({
                        "pattern": pattern,
                        "found": match,
                        "in_context": False,
                    })

    return {
        "is_safe": len(flags_found) == 0,
        "flags": flags_found,
        "flag_count": len(flags_found),
    }


def get_safe_fallback(question: str, reason: str) -> dict:
    fallback_messages = {
        "no_chunks_found": (
            "I don't have information on this specific topic in my knowledge base yet. "
            "For accurate guidance, please consult your obstetrician, pediatrician, "
            "or an Ayurvedic practitioner. You can also call the NHM helpline: 104."
        ),
        "low_relevance": (
            "I found some related information, but I'm not confident enough to give "
            "you a reliable answer on this specific question. This is an area where "
            "you should speak directly with your doctor. "
            "NHM helpline: 104 | FOGSI helpline: available at fogsi.org"
        ),
        "hallucination_detected": (
            "I want to give you accurate information, but I'm not able to verify "
            "all the details needed for this answer from my knowledge sources. "
            "Please consult a qualified healthcare provider for this question."
        ),
        "requires_doctor": (
            "This question involves medical decisions that need personalised advice "
            "from a qualified doctor. I cannot provide a safe automated answer for this. "
            "Please consult your healthcare provider directly."
        ),
    }

    answer = fallback_messages.get(reason, fallback_messages["no_chunks_found"])
    answer += DISCLAIMERS["safety_fallback"]

    return {
        "answer": answer,
        "sources": [],
        "confidence": "safety_fallback",
        "category": "safety_fallback",
        "hallucination_check": "triggered",
        "reason": reason,
    }


def _append_disclaimer(answer: str, tier: str) -> str:
    disclaimer = DISCLAIMERS.get(tier, DISCLAIMERS["ai_generated"])
    return answer + disclaimer


def generate_response(
    question: str,
    category: str = "general",
    ner_context: dict = None,
) -> dict:
    try:
        model, collection = _get_embeddings()

        q_vec = model.encode([question]).tolist()
        query_kwargs = {"query_embeddings": q_vec, "n_results": 5}
        if category != "general":
            query_kwargs["where"] = {"category": category}

        results = collection.query(**query_kwargs)

        confidence_check = check_retrieval_confidence(results)
        if not confidence_check["should_answer"]:
            return get_safe_fallback(question, confidence_check["reason"])

        chunks = results["documents"][0]
        sources = [m["source"] for m in results["metadatas"][0]]
        cats = [m["category"] for m in results["metadatas"][0]]
        retrieval_score = confidence_check["score"]

        tier = classify_confidence_tier(question, retrieval_score, category)

        if tier == "requires_doctor":
            fallback = get_safe_fallback(question, "requires_doctor")
            fallback["confidence"] = "requires_doctor"
            fallback["queue_for_doctor"] = True
            return fallback

        context = "\n\n".join(
            [
                f"[Source: {src} | {cat}]\n{chunk}"
                for src, cat, chunk in zip(sources, cats, chunks)
            ]
        )

        user_context = ""
        if ner_context:
            if ner_context.get("pregnancyWeek"):
                user_context += f"User is {ner_context['pregnancyWeek']} weeks pregnant. "
            if ner_context.get("babyAgeMonths"):
                user_context += f"Baby is {ner_context['babyAgeMonths']} months old. "
            if ner_context.get("conditions"):
                user_context += (
                    f"Known conditions: {', '.join(ner_context['conditions'])}. "
                )

        user_prompt = f"""USER CONTEXT: {user_context or 'Not provided'}

KNOWLEDGE BASE CONTEXT:
{context}

QUESTION: {question}"""

        response = _get_groq_client().chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": GROUNDED_SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=800,
            temperature=0.3,
        )

        answer = response.choices[0].message.content

        hallucination_check = detect_potential_hallucination(answer, chunks)
        if not hallucination_check["is_safe"]:
            logger.warning(
                "Hallucination flags detected: %s",
                hallucination_check["flags"],
            )
            return get_safe_fallback(question, "hallucination_detected")

        answer = _append_disclaimer(answer, tier)

        return {
            "answer": answer,
            "sources": list(set(sources)),
            "confidence": tier,
            "category": category,
            "retrieval_score": retrieval_score,
            "hallucination_check": "passed",
        }

    except Exception as e:
        logger.error("Response generation error: %s", e)
        return {
            "answer": (
                "I'm having technical difficulties right now. "
                "Please try again in a moment, or consult your doctor directly. "
                "NHM Helpline: 104"
            )
            + DISCLAIMERS["safety_fallback"],
            "sources": [],
            "confidence": "requires_doctor",
            "category": category,
            "error": True,
        }
